#For help visit: https://comingsoon.com
Title: true

TitlePublic: false
VipTitlePublic: true
StaffTitlePublic: true

CustomJoin: true
CustomLeave: true

FixSkins: true
EnableSkinsPerms: false

HumanVerify: true

Motd: true

OpProtect: false

IpProtect: true
IpPunishType: kick

JoinLighting: true

ForceLighting: Staff

UsePlayerPermAsLighting: false

UseVipPermAsLighting: false

UseStaffPermAsLighting: false

JoinExplosion: true

ForceExplosion: Staff

UsePlayerPermAsExplosion: false

UseVipPermAsExplosion: false

UseStaffPermAsExplosion: false

EnderDragonEffects: false

Permissions:
  User: welcome.user
  Lighting: welcome.lighting
  Explosion: welcome.explosion
  Skin: welcome.skin
  Vip: welcome.vip
  Staff: welcome.staff
  Op: welcome.op
  OpWarn: welcome.opwarn


reload: "&aPlugin reloaded"

TitleMessage: "&9{server} &7{online}&f/&8{max}"
Subtitle: "&b{player}"

VipTitle: "&8&l[&eVip&8&l]"
VipSubtitle: "&b{vip}"

StaffTitle: "&8&l[&c&lStaff&8&l]"
StaffSubtitle: "&b{staff}"

Join: "&8&l[&b+&8&l] &7{player}"
Leave: "&8&l[&c-&8&l] &7{player}"

Separator: "&8&l&m-----------------------------------"
MotdMessage:
  - "&aWelcome to server"
  - "&cMrTest"
  - "&b{player}"

NewsTitle: "&a&lNEWS"

News:
  - "&aPlugin enabled"
  - "&cNews 2"
  - "&bTest"

Kick: "&cYou are not a verified operator"

IpPunish: "&bYou've been kicked {doubleline} &4&lYOUR IP ISN'T THE SAME THAT THE LAST, VPN IS NOT ALLOWED ON THE SERVER {doubleline} &bReconnect again if you want to play"

VerifyKick: "&8&l( &aHuman verification &8&l) {doubleline} &bReconnect to play"

OpProtectionOffWarning: "&bThe player &c{player}&b has op, if he isn't a staff member, you should ban him"

DragonBarMessage: "&b{player} &7has joined &b{online}&f/&3{max}"